# vars = [
#     "nome",
#     "cognome",
#     "id_personale",
#     "data_nascita",
#     "indirizzo_residenza",
#     "numero_telefono",
#     "email",
#     "conto_bancario",
#     "carta_credito",
#     "dati_biometrici",
#     "codice_sanitario",
#     "dati_genetici",
#     "info_assicurazioni",
#     "credenziali_accesso",
#     "abitudini_navigazione",
#     "condanne_penali",
#     "preferenze_sessuali",
#     "opinioni_politiche",
#     "partito",
#     "appartenenza_sindacale",
#     "sindacato",
#     "origine_etnica",
#     "dati_religiosi",
#     "nome_madre",
#     "nome_padre",
#     "nome_coniuge",
#     "nome_figli",
#     "patente",
#     "targa",
#     "stipendio",
#     "titolo_studio",
#     "occupazione",
#     "numero_contratto",
#     "indirizzo_lavoro",
#     "posizione_geografica",
#     "immagini_personali",
#     "video_personali",
#     "personale",
#     "personali",
#     "stato_civile",
#     "cittadinanza",
#     "data_assunzione",
#     "data_licenziamento",
#     "numero_sicurezza_sociale",
#     "codice_fiscale",
#     "info_previdenziali",
#     "info_patrimoniali",
#     "dati_immobiliari",
#     "debiti",
#     "crediti",
#     "numero_ricetta_medica",
#     "dati_ospedalieri",
#     "info_famigliare",
#     "info_amici",
#     "profilo_social_media",
#     "numero_tessera_elettorale",
#     "dati_impronte_digitali",
#     "codice_cliente",
#     "codice_utente",
#     "numero_polizza",
#     "numero_pensione",
#     "numero_conto_corrente",
#     "codice_IBAN",
#     "codice_BIC",
#     "numero_fax",
#     "numero_cellulare",
#     "indirizzo_IP",
#     "MAC_address",
#     "nazione_residenza",
#     "regione_residenza",
#     "città_residenza",
#     "codice_postale",
#     "dati_scolastici",
#     "numero_passaporto",
#     "data_rilascio_passaporto",
#     "data_scadenza_passaporto",
#     "info_fidelizzazione",
#     "codice_fiscale_estero",
#     "dati_ambientali",
#     "dati_dispositivi",
#     "info_contratti",
#     "info_rendiconti"

# ]

vars = [
    "Full name",
    "Social security number",
    "Driver's license number",
    "Passport number",
    "Home address",
    "Email address",
    "Phone number",
    "Work address",
    "GPS coordinates",
    "IP geolocation",
    "Social media check-ins",
    "IP address",
    "Cookie identifiers",
    "RFID tags",
    "User account names",
    "Fingerprints",
    "Facial recognition data",
    "Retinal scans",
    "Voice patterns",
    "Medical history",
    "Prescription information",
    "Mental health records",
    "Fitness tracker data",
    "DNA profiles",
    "Genetic test results",
    "Family medical history",
    "Age or date of birth",
    "Gender",
    "Race or ethnicity",
    "Education level",
    "Employment history",
    "Income or financial data",
    "Marital status",
    "Political party affiliation",
    "Religious denomination",
    "Participation in political or religious events",
    "Donations to political or religious organizations",
    "Sexual preference",
    "Relationship status",
    "Dating app profiles",
    "Browsing history",
    "Purchase history",
    "Social media activity",
    "App usage data",
    "Job title",
    "Employer name",
    "Professional certifications",
    "Work performance data"
]